export const ADD_BLOG_POST = "ADD_BLOG_POST";
export const EDIT_BLOG_POST = "EDIT_BLOG_POST";
export const DELETE_BLOG_POST = "DELETE_BLOG_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";